### ISSUE TITLE
Non-associative operators

### ISSUE THREAD

**Issue by sloane-shark** [segeljakt/pratt#3]
Is it possible to support non-associative operators with `pratt`, such that comparison operators can either support complex chaining (`x == y == z` => `x == y && y == z`) or forbid repeated comparisons like that, issuing a parse error?

**Comment by segeljakt** [comment]
Good point, sorry I missed the issue notification. I will look into it, it should not be too hard

**Comment by segeljakt** [comment]
I added an `Associativity::Neither` variant which you can use for non-associative operators like `==`. If you have a string `"x == y == z"` which produces the tokens `[x, ==, y, ==, z]`, Pratt will parse the three first tokens into a binary operation and leave the last two untouched.

**Comment by segeljakt** [comment]
@matthewess Is this an OK approach? I have not uploaded the new version to crates.io yet but can do it if you would like. Also, I added so that the parser cannot panic, instead it will return a `Result<Expr,PrattError>`

**Comment by sloane-shark** [comment]
That looks perfect! Exactly along the lines of what I was thinking I might have to implement myself :smile:

**Comment by segeljakt** [comment]
Alright, the new version should now be published 🤩  let me know if you come across any issues.

**Comment by sloane-shark** [comment]
Hey @segeljakt, thanks again for adding this feature. I'm now getting around to trying to implement comparison operator chaining with it. Is the basic idea that I tag the chaining operators with `Neither`, then in `infix` I would inspect `lhs` (and `rhs`?) to see if they're chainable with the current operator and modify the output structure accordingly? (I can provide links to the relevant parts of my project or a more minimal example if that would help)

EDIT: I think the trouble I'm having is I can't seem to do anything to the tokens you mentioned would be "untouched". In `infix`, I can only see up to the next primary value. Do I have to handle the chaining logic at the main-language parser level, rather than inside of my pratt parsing code? Here are some relevant sections of the code I'm working on: https://gitlab.com/-/snippets/2035984

EDIT2: With a bit of experimenting, it seems like I was right. I think I am probably meant to call the `parse` method, examine the token stream to see if I have more chainable operators to parse, and then `parse` again after doing whatever processing I need to do? I think this will end up being pretty unwieldy for what I'm trying to do, unless I misunderstand things. My guess is I could probably accomplish close to what I want by just changing the associativity of comparisons to `Left`, and processing them as I currently am so that they go into `Expr::Cmp` nodes instead of normal `Expr::Binary` nodes. Let me know if you have any recommendations for how to approach this, the outcome I am trying to achieve at this point is Python-style comparison chaining.

**Comment by segeljakt** [comment]
Hi, I am very sorry for the late reply. [Here](https://www.geeksforgeeks.org/operator-precedence-and-associativity-in-c/) it says relational operators are parsed as left-associative. I think it makes sense to parse them as left (or right)-associative and then in a separate desugaring pass over the AST replace expressions which are `Expr::Cmp(Expr::Cmp(a, b), c)` with `Expr::And(Expr::Cmp(a, b), Expr::Cmp(b, c))`. The `Associativity::Neither` might be more useful if you are trying to reject programs where you have `a == b == c`.
