### ISSUE TITLE
Mutable reference to iterator in primary function

### ISSUE THREAD

**Issue by TimUntersberger** [segeljakt/pratt#4]
First I want to say that this project is really cool! It is a real pleasure to work with for now without having to understand how pratt parsing works exactly.

Could you pass the mutable reference of the iterator to the primary function? This would make it possible to keep the token stream flat while still supporting grouping.

**example (pseudo code)**

expr
```
(1 + 2) * 3
```

code
```python
if token is '(' then
  save tokens until matching ')'
  parse the found tokens and return result
end
```

result
```lisp
("*" ("+" 1 2) 3)
```

**example (how it could look like)**

expr
```
(1 + 2) * 3
```

code
```rust
    fn primary(&mut self, iter: &mut I, token: Self::Input) -> pratt::Result<Self::Output> {
        Ok(match token {
            Token::NumberLiteral(data) => Expression::NumberLiteral(data.value),
            Token::LParan(_) => {
                let mut depth = 0;
                let mut tokens = Vec::new();

                while let Some(token) = iter.next() {
                    match token {
                        Token::LParan(_) => { depth += 1; },
                        Token::RParan(_) => {
                            if depth == 0 {
                                break;
                            } else {
                                depth -= 1;
                            }
                        },
                        token => {
                            tokens.push(token);
                        }
                    }
                }

                self.parse(tokens, iter)
            },
            _ => unreachable!(),
        })
    }
```

result
```lisp
("*" ("+" 1 2) 3)
```

**Comment by TimUntersberger** [comment]
~~Could you also please give me some pointers as to how you would implement a parser for this expression?~~

```
a + test()
```

~~`test()` evaluates to `test` when I implement it myself.~~

**Comment by TimUntersberger** [comment]
Note to self: for parsing function calls do the same as with expression grouping

**Comment by segeljakt** [comment]
Hi, thank you for the suggestion and code. It should definitely be possible, I'll take a look at it 👍

**Comment by TimUntersberger** [comment]
@segeljakt I can just open a PR with the changes, because I already the changed the things I needed.

**Comment by segeljakt** [comment]
Please do! 🙂
